version: '2.4'
services:
  app:
    build: .
    image: internship_qualifier
    mem_reservation: "1024m"
    ports:
      - 3000
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4.5
    restart: always
    expose:
      - '27017'
